version: "3.8"
services:
  server:
    image: "nginx:1.29.2-alpine"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  php:
    build:
      context: .
      dockerfile: dockerfile/php.dockerfile
    volumes:
      - ./src:/var/www/html
    
  mysql:
    image: "mysql"
    env_file:
      - ./env/mysql.env
  
  composer:
    build:
      context: .
      dockerfile: dockerfile/composer.dockerfile
    volumes:
      - ./src:/var/www/html

    
  